[2022-12-22T13:54:53.437+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.RunAPIService manual__2022-12-22T13:54:34.577275+00:00 [queued]>
[2022-12-22T13:54:53.451+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.RunAPIService manual__2022-12-22T13:54:34.577275+00:00 [queued]>
[2022-12-22T13:54:53.451+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-22T13:54:53.451+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-22T13:54:53.451+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-22T13:54:53.468+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): RunAPIService> on 2022-12-22 13:54:34.577275+00:00
[2022-12-22T13:54:53.475+0000] {standard_task_runner.py:55} INFO - Started process 12321 to run task
[2022-12-22T13:54:53.478+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'co2balance', 'RunAPIService', 'manual__2022-12-22T13:54:34.577275+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/co2balance.py', '--cfg-path', '/tmp/tmpe3helnnc']
[2022-12-22T13:54:53.480+0000] {standard_task_runner.py:83} INFO - Job 115: Subtask RunAPIService
[2022-12-22T13:54:53.568+0000] {task_command.py:389} INFO - Running <TaskInstance: co2balance.RunAPIService manual__2022-12-22T13:54:34.577275+00:00 [running]> on host 1a27c7ed0719
[2022-12-22T13:54:53.669+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=CO2balance
AIRFLOW_CTX_DAG_ID=co2balance
AIRFLOW_CTX_TASK_ID=RunAPIService
AIRFLOW_CTX_EXECUTION_DATE=2022-12-22T13:54:34.577275+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-22T13:54:34.577275+00:00
[2022-12-22T13:54:53.834+0000] {logging_mixin.py:137} WARNING - ERROR:    Error loading ASGI app. Could not import module "co2balance_api_service".
[2022-12-22T13:54:53.850+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-22T13:54:53.881+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
