[2022-12-22T11:16:16.685+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.RunAPIService manual__2022-12-22T11:15:56.874446+00:00 [queued]>
[2022-12-22T11:16:16.698+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.RunAPIService manual__2022-12-22T11:15:56.874446+00:00 [queued]>
[2022-12-22T11:16:16.699+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-22T11:16:16.699+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-22T11:16:16.699+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-22T11:16:16.723+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): RunAPIService> on 2022-12-22 11:15:56.874446+00:00
[2022-12-22T11:16:16.732+0000] {standard_task_runner.py:55} INFO - Started process 4641 to run task
[2022-12-22T11:16:16.738+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'co2balance', 'RunAPIService', 'manual__2022-12-22T11:15:56.874446+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/co2balance.py', '--cfg-path', '/tmp/tmpie3gqke3']
[2022-12-22T11:16:16.740+0000] {standard_task_runner.py:83} INFO - Job 109: Subtask RunAPIService
[2022-12-22T11:16:16.852+0000] {task_command.py:389} INFO - Running <TaskInstance: co2balance.RunAPIService manual__2022-12-22T11:15:56.874446+00:00 [running]> on host 1a27c7ed0719
[2022-12-22T11:16:16.982+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=CO2balance
AIRFLOW_CTX_DAG_ID=co2balance
AIRFLOW_CTX_TASK_ID=RunAPIService
AIRFLOW_CTX_EXECUTION_DATE=2022-12-22T11:15:56.874446+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-22T11:15:56.874446+00:00
[2022-12-22T11:16:17.152+0000] {logging_mixin.py:137} WARNING - ERROR:    Error loading ASGI app. Could not import module "co2balance_api_service".
[2022-12-22T11:16:17.197+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-22T11:16:17.244+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
