[2022-12-20T14:28:47.610+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.CleanData manual__2022-12-20T14:28:45.471868+00:00 [queued]>
[2022-12-20T14:28:47.635+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.CleanData manual__2022-12-20T14:28:45.471868+00:00 [queued]>
[2022-12-20T14:28:47.636+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-20T14:28:47.636+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-20T14:28:47.636+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-20T14:28:47.670+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): CleanData> on 2022-12-20 14:28:45.471868+00:00
[2022-12-20T14:28:47.678+0000] {standard_task_runner.py:55} INFO - Started process 776 to run task
[2022-12-20T14:28:47.687+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'co2balance', 'CleanData', 'manual__2022-12-20T14:28:45.471868+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/co2balance.py', '--cfg-path', '/tmp/tmpzi0b8t0n']
[2022-12-20T14:28:47.689+0000] {standard_task_runner.py:83} INFO - Job 19: Subtask CleanData
[2022-12-20T14:28:47.882+0000] {task_command.py:389} INFO - Running <TaskInstance: co2balance.CleanData manual__2022-12-20T14:28:45.471868+00:00 [running]> on host 1a27c7ed0719
[2022-12-20T14:28:48.080+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=CO2balance
AIRFLOW_CTX_DAG_ID=co2balance
AIRFLOW_CTX_TASK_ID=CleanData
AIRFLOW_CTX_EXECUTION_DATE=2022-12-20T14:28:45.471868+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-20T14:28:45.471868+00:00
[2022-12-20T14:28:48.631+0000] {clean_project_file.py:17} INFO - Data read from excel file completed successfully
[2022-12-20T14:28:48.635+0000] {clean_project_file.py:54} INFO - Read headers from excel file completed successfully
[2022-12-20T14:28:48.637+0000] {clean_project_file.py:88} INFO - Renamed headers from excel file completed successfully
[2022-12-20T14:28:49.075+0000] {clean_project_file.py:107} INFO - Data cleaned into dataframe successfully
[2022-12-20T14:28:49.145+0000] {clean_project_file.py:109} INFO - Data written to excel file successfully
[2022-12-20T14:28:49.145+0000] {python.py:177} INFO - Done. Returned value was:                 start_date                end_date  ...       sector      cell
0  2022-09-20 09:57:59.685 2022-09-20 10:15:16.341  ...       Ruhuha   Kindama
1  2022-09-20 09:58:52.014 2022-09-20 10:05:38.519  ...   Nyarugenge    Ngenda
2  2022-09-20 08:10:21.357 2022-09-20 08:28:54.976  ...      Gashora  Kagomasi
3  2022-09-20 11:18:45.457 2022-09-20 11:27:44.064  ...   Nyarugenge   Rugando
4  2022-09-20 07:53:20.948 2022-09-20 08:35:24.522  ...      Ngeruka    Murama
..                     ...                     ...  ...          ...       ...
79 2022-09-20 11:06:04.712 2022-09-20 13:57:40.288  ...    Bushekeri     Ngoma
80 2022-09-20 11:20:56.753 2022-09-20 13:43:06.595  ...  Nyabitekeri  Kigabiro
81 2022-09-20 08:52:29.053 2022-09-20 09:14:14.454  ...    Bushekeri     Ngoma
82 2022-09-20 10:12:10.674 2022-09-20 13:43:42.834  ...  Nyabitekeri  Kigabiro
83 2022-09-20 09:14:46.433 2022-09-20 09:45:06.431  ...       Shangi    Mugera

[84 rows x 29 columns]
[2022-12-20T14:28:49.196+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2022-12-20T14:28:49.197+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2022-12-20T14:28:49.213+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=co2balance, task_id=CleanData, execution_date=20221220T142845, start_date=20221220T142847, end_date=20221220T142849
[2022-12-20T14:28:49.225+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 19 for task CleanData (Object of type DataFrame is not JSON serializable; 776)
[2022-12-20T14:28:49.273+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-20T14:28:49.297+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
